### PR TITLE
configurable adc pins

### PR DESCRIPTION
**Pull request by bikemike**
Made adc pins configurable. 

I was not sure about the line:

ADC_InitStructure.ADC_Channel_Number = size; 

And the other three adc pins that were configured.

Also I did not test with H8mini since I do not have one.

### CODE REVIEW

**Comment by silver13** [comment]
Ok, I can't get it to work ( zero readout ) , I'll have to read the datasheet and try again sometime soon.

I can't find any reason why it shouldn't work, but I do remember the adc did not work the way I expected it to when I originally coded it. The channel order/ scan direction seemed wrong

**Comment by bikemike** [comment]
Strange. Did I get the wrong pin(PA5)?

The FQ777-124 uses PA2 and this code flashed to it works with the defines set to PA2.

**Comment by silver13** [comment]
It's weird, I tried to fix it but didn't work, then I ended up removing the other 3 adc inputs from the original driver, leaving only one, that worked fine. Should be PA5, too.

I should look into it again tomorrow, I also realised that since only one input is used, it's probably easier to just simplify the whole thing

**Comment by silver13** [comment]
It was because one of the adc calls form main had old adc channel number, it's all good now, added

**Comment by bikemike** [comment]
whoops. sorry about that. i must have missed that line when i merged from my fq777-124 branch. glad you got it sorted out.

**Pull request merged**
