### PR TITLE
Used motor defines to clarify code.

### PR DESCRIPTION
**Pull request by markusgritsch**
With this change the Dshot driver looks the same on H8 and H101 firmwares.

### CODE REVIEW

**Comment by silver13** [comment]
I don't know if this is a good idea, because then changing the motor order defines won't change the motor order any more for d-shot

on the other hand the changing of defines is rarely used anyway, what do you think?

**Comment by markusgritsch** [comment]
I think the switch statement in drv_esc and drv_pwm should also use the motor defines. IMO FL, FR, BL, BR are tied to specific MCU pins anyways, and if the motor defines are used everywhere, they determine only the location in an array and have no influence else. But maybe I don't understand enough of the inner workings of your code :)

**Comment by silver13** [comment]
If you use the gyro rotate options, then the motor order will be incorrect, as it's technically referenced to the gyro orientation. So the defines can be changed to make the order correct.

The motor order is used for the X9 "hack" iirc

**Comment by silver13** [comment]
I wish I could have made it all more organized, but that is something that has to be done before it's all written, in the planning stage.

Mainly the use of global variables defined in different files is confusing imo

**Comment by markusgritsch** [comment]
Hmm, I thought the different gyro orientation of the H8 and H101 is accounted for by the different default defines of SENSOR_ROTATE_90_CCW in the H101 code and SENSOR_ROTATE_180 in the H8 code. Well, it seems I don't understand it enough :)

Alas, it would have "fixed" the difference between the two Dshot implementations. So I will close this pull request.

And regarding the code organization: Don't worry, it's not bad at all. And at least it flies well ;)

**Pull request closed without merging**
